branches: 
  - main
repositoryUrl: https://github.com/liatrio/image-runner-lead-terraform.git
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
